### ISSUE TITLE
components.yaml is incomplete

### ISSUE THREAD

**Issue by mathomp4** [bena-nasa/GEOS_topography_workflow#2]
As found by @weiyuan-jiang, the `components.yaml` is missing a fixture statement. This might be something from mepo 2 that older mepo allowed?

To wit, the top of the `components.yaml` needs something like:
```yaml
GEOS_topography_workflow:
  fixture: true
  develop: main
```
